### ISSUE TITLE
Reading Nested List

### ISSUE THREAD

**Issue by mpekalski** [tapanalyticstoolkit/spark-tensorflow-connector#31]
I am not sure is it the right place to ask this question, but how would I read nested list from tfrecord?
In particular I am tryring to process frame level data from https://research.google.com/youtube8m/download.html

So "rgb" would have a list of lists, see below. 
```
feature_lists: {
  feature_list: {
    key  : "rgb"
    value: {
      feature: {
        bytes_list: {
          value: [1024 8bit quantized features]
        }
      }
      feature: {
        bytes_list: {
          value: [1024 8bit quantized features]
        }
      }
      ... # Repeated for every second of the video, up to 300
  }
  feature_list: {
```

I tried reading it as `StructField("rgb",  ArrayType(ArrayType(DoubleType, true), true))` but it did not work. Any ideas?

**Comment by karthikvadla** [comment]
@mpekalski : Please use this repo for any issues and questions. This is our active repo.  https://github.com/tensorflow/ecosystem/tree/master/spark.

Sure will look into it.

**Comment by skavulya** [comment]
@mpekalski We created an issue in https://github.com/tensorflow/ecosystem/issues/36. We are working on the PR.

**Comment by skavulya** [comment]
The fix has been merged to the TensorFlow ecosystem repo
